uidemos:
    image: docker.xxx.com/uidemos:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - APPENTRY=index.html
      - CLIENTID=callback
      - VIYA_SERVER-your-viya-server

